version: '3.8'

services:
  citymotion:
    build: .
    container_name: citymotion-app
    ports:
      - "9002:9002"
      - "3001:3001"
    volumes:
      # Persistência do banco de dados no pendrive
      - ./backend/database:/app/backend/database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
